import { Poppins } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
import Navbar from '@/components/Navbar';
import Drawer from '@/components/Drawer';
import AddContent from '@/components/AddContent';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <Navbar />
        <div className="pt-16" />
        {children}
        <AddContent />
        <Drawer />
        <Script id="theme-script" strategy="beforeInteractive">
          {`
    (function () {
      try {
        var stored = localStorage.getItem('markdown-renderer');
        var theme = 'light';
        if (stored) {
          var parsed = JSON.parse(stored);
          theme = parsed.state?.theme || 'light';
        }
        document.documentElement.setAttribute('data-theme', theme);
        document.cookie = 'theme=' + theme + '; path=/; max-age=31536000';
      } catch (e) {
        document.documentElement.setAttribute('data-theme', 'light');
        document.cookie = 'theme=light; path=/; max-age=31536000';
      }
    })();
  `}
        </Script>
      </body>
    </html>
  );
}
